#include "pch.h"

#include "ParkMiller.h"
#include "RandomParkMiller.h"

namespace random_generators
{
	// Constants for the Park-Miller random number generator algorithm.
	constexpr long a = 16807; // Multiplier.
	constexpr long m = 2147483647; // Modulus (2^31 - 1, a Mersenne prime).
	constexpr long q = 127773; // m div a (m divided by a).
	constexpr long r = 2836; // m mod a (remainder of m divided by a).

	// Constructor for the Park-Miller random number generator with an initial seed.
	park_miller::park_miller(const long seed) : seed_(seed)
	{
		if (seed_ == 0) // Seed must not be zero, if so, set to 1.
		{
			seed_ = 1;
		}
	}

	// Method to generate the next random integer in the sequence.
	long park_miller::get_one_random_integer()
	{
		const long k = seed_ / q; // Calculate quotient of seed_ divided by q.
		// Calculate new seed using the Park-Miller algorithm.
		seed_ = a * (seed_ - k * q) - r * k;

		if (seed_ < 0) // If seed is negative, make it positive.
		{
			seed_ += m;
		}

		return seed_; // Return the new random seed.
	}

	// Method to set a new seed for the random number generator.
	void park_miller::set_seed(const long new_seed)
	{
		seed_ = new_seed;
		if (seed_ == 0) // Ensure the new seed is not zero.
		{
			seed_ = 1;
		}
	}

	// Returns the maximum possible value generated by this generator.
	unsigned long park_miller::max()
	{
		return m - 1; // Maximum is m-1 since we never want to return m itself.
	}

	// Returns the minimum possible value generated by this generator.
	unsigned long park_miller::min()
	{
		return 1; // Minimum is 1 since we never want to return 0.
	}
}


/*
 * This portion of code is adapted from Mark Joshi's work in "C++ Design Patterns and Derivatives Pricing".
 * Copyright (c) 2002 Mark Joshi
 *
 * Permission to use, copy, modify, distribute and sell this
 * software for any purpose is hereby granted without fee, provided that the above copyright notice
 * appear in all copies and that both that copyright notice and
 * this permission notice appear in supporting documentation.
 * Mark Joshi makes no representations about the
 * suitability of this software for any purpose. It is provided
 * "as is" without express or implied warranty.
 */
