#pragma once

#include "randomBase.h"
#include "NumericArray.h"

// Namespace for random number generator classes.
namespace random_generators
{
	// Implements the Park-Miller random number generator algorithm.
	class park_miller
	{
	public:
		// Constructs a Park-Miller generator with an optional seed (default is 1).
		explicit park_miller(long seed = 1);

		// Generates and returns a pseudo-random integer.
		long get_one_random_integer();
		// Sets the seed of the random number generator to a new value.
		void set_seed(long new_seed);
		// Retrieves the maximum possible value generated by the Park-Miller RNG.
		static unsigned long max();
		// Retrieves the minimum possible value generated by the Park-Miller RNG.
		static unsigned long min();

	private:
		long seed_; // The current seed value for generating random numbers.
	};
}
